config/routes.rb
Rails.application.routes.draw do
  
  resources :groups

  devise_for :users
  
  resources :memos

  resources :events

  resources :contacts

  get '/c/:id', to: 'home#contact', as: 'contact_edit'

  root 'home#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  obfuscate_id :spin => 104010

  belongs_to :user
  belongs_to :group
  # for protected_attributes
  attr_accessible :user_id, :group_id, :first_name, :last_name, :birthday, :email, :celphone, :phone, :address, :comments


  def fullname
    "#{last_name} #{first_name}"
  end

  def o_id
    ObfuscateId.hide(id, self.class.obfuscate_id_spin)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  obfuscate_id :spin => 104010

  belongs_to :user
  belongs_to :contact
  # for protected_attributes
  attr_accessible :user_id, :contact_id, :event_date, :name, :comments, :remember
end

app/models/group.rb
class Group < ActiveRecord::Base
  obfuscate_id :spin => 104010

  belongs_to :user
  # for protected_attributes
  attr_accessible :user_id, :name, :description
end

app/models/memo.rb
class Memo < ActiveRecord::Base
  obfuscate_id :spin => 104010

  belongs_to :user
  # for protected_attributes
  attr_accessible :user_id, :content, :archived
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # for protected_attributes
  attr_accessible  :fullname, :celphone, :phone, :email, :encrypted_password, :reset_password_token, :reset_password_sent_at, :remember_created_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index

    unless params[:text].blank?

      s = "%#{params[:text]}%"

      @contacts = Contact.where("last_name LIKE ? OR first_name LIKE ? OR email LIKE ?", s, s, s)


      data = []
      @contacts.each do |c|
        data << {id: c.o_id, fullname: c.fullname}
      end

    end
    
    render text:data.to_json
  end

  def show
    respond_with(@contact)
  end

  def new
    @contact = Contact.new
    respond_with(@contact)
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    @contact.save

    redirect_to root_path
  end

  def update
    @contact.update(contact_params)
    redirect_to contact_edit_path(@contact.id)
  end

  def destroy
    @contact.destroy
    respond_with(@contact)
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:group_id, :first_name, :last_name, :birthday, :email, :celphone, :phone, :address, :comments)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:contact_id, :event_date, :name, :comments, :remember)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.save
    respond_with(@group)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @contacts = Contact.all
    @contact = Contact.new


  end

  def contact
    @contacts = Contact.all
    @contact = Contact.find(params[:id])
    
    render :index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  def index
    @memos = Memo.all
    respond_with(@memos)
  end

  def show
    respond_with(@memo)
  end

  def new
    @memo = Memo.new
    respond_with(@memo)
  end

  def edit
  end

  def create
    @memo = Memo.new(memo_params)
    @memo.save
    respond_with(@memo)
  end

  def update
    @memo.update(memo_params)
    respond_with(@memo)
  end

  def destroy
    @memo.destroy
    respond_with(@memo)
  end

  private
    def set_memo
      @memo = Memo.find(params[:id])
    end

    def memo_params
      params.require(:memo).permit(:content, :archived)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def body_class
    "#{controller_name}_#{action_name}"
  end

  def title(page_title, show_title = true )
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def raw_title
    tag_title = ""

    tag_title += "#{content_for(:title)} | #{company_name} - RAP" if content_for?(:title)
    tag_title
  end

  def show_title?
    @show_title
  end

  def flash_class(level)
    case level
      when "notice" then "alert-info"
      when "success" then "alert-success"
      when "error" then "alert-danger"
      when "alert" then "alert-danger"
    end
  end
  
end

app/views/contacts/_form.html.slim
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      h2 = "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      ul
        - @contact.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :group
    = f.text_field :group
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :birthday
    = f.date_select :birthday
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :celphone
    = f.text_field :celphone
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :address
    = f.text_area :address
  .field
    = f.label :comments
    = f.text_area :comments
  .actions = f.submit 'Save'

app/views/contacts/edit.html.slim
h1 Editing contact

== render 'form'

= link_to 'Show', @contact
'|
= link_to 'Back', contacts_path

app/views/contacts/index.html.slim
h1 Listing contacts

table
  thead
    tr
      th Group
      th First name
      th Last name
      th Birthday
      th Email
      th Celphone
      th Phone
      th Address
      th Comments
      th
      th
      th

  tbody
    - @contacts.each do |contact|
      tr
        td = contact.group
        td = contact.first_name
        td = contact.last_name
        td = contact.birthday
        td = contact.email
        td = contact.celphone
        td = contact.phone
        td = contact.address
        td = contact.comments
        td = link_to 'Show', contact
        td = link_to 'Edit', edit_contact_path(contact)
        td = link_to 'Destroy', contact, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.slim
h1 New contact

== render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.slim
p#notice = notice

p
  strong Group:
  = @contact.group
p
  strong First name:
  = @contact.first_name
p
  strong Last name:
  = @contact.last_name
p
  strong Birthday:
  = @contact.birthday
p
  strong Email:
  = @contact.email
p
  strong Celphone:
  = @contact.celphone
p
  strong Phone:
  = @contact.phone
p
  strong Address:
  = @contact.address
p
  strong Comments:
  = @contact.comments

= link_to 'Edit', edit_contact_path(@contact)
'|
= link_to 'Back', contacts_path

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :contact
    = f.text_field :contact
  .field
    = f.label :event_date
    = f.date_select :event_date
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :comments
    = f.text_area :comments
  .field
    = f.label :remember
    = f.check_box :remember
  .actions = f.submit 'Save'

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

= link_to 'Show', @event
'|
= link_to 'Back', events_path

app/views/events/index.html.slim
h1 Listing events

table
  thead
    tr
      th Contact
      th Event date
      th Name
      th Comments
      th Remember
      th
      th
      th

  tbody
    - @events.each do |event|
      tr
        td = event.contact
        td = event.event_date
        td = event.name
        td = event.comments
        td = event.remember
        td = link_to 'Show', event
        td = link_to 'Edit', edit_event_path(event)
        td = link_to 'Destroy', event, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Event', new_event_path

app/views/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice = notice

p
  strong Contact:
  = @event.contact
p
  strong Event date:
  = @event.event_date
p
  strong Name:
  = @event.name
p
  strong Comments:
  = @event.comments
p
  strong Remember:
  = @event.remember

= link_to 'Edit', edit_event_path(@event)
'|
= link_to 'Back', events_path

app/views/groups/_form.html.slim
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      h2 = "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      ul
        - @group.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit 'Save'

app/views/groups/edit.html.slim
h1 Editing group

== render 'form'

= link_to 'Show', @group
'|
= link_to 'Back', groups_path

app/views/groups/index.html.slim
h1 Listing groups

table
  thead
    tr
      th Name
      th Description
      th
      th
      th

  tbody
    - @groups.each do |group|
      tr
        td = group.name
        td = group.description
        td = link_to 'Show', group
        td = link_to 'Edit', edit_group_path(group)
        td = link_to 'Destroy', group, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Group', new_group_path

app/views/groups/new.html.slim
h1 New group

== render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.slim
p#notice = notice

p
  strong Name:
  = @group.name
p
  strong Description:
  = @group.description

= link_to 'Edit', edit_group_path(@group)
'|
= link_to 'Back', groups_path

app/views/home/index.html.slim
- content_for :footer do
  javascript:
    $('#clients').on('change', function() {
      var url = "/c/";
      redirect_to(url + this.value + "#contacts" );
    });


    $("#search").on("keyup", function() {
      
      var text_search = $(this).val();

      if (text_search.length > 3) {
        $.getJSON( '/contacts.json', {
          text: $(this).val(),
          ajax: "true"
        }, function(j) {
          var i, options;
          options = "";
          i = 0;
          while (i < j.length) {
            options += "<option value=\"" + j[i].id + "\">" + j[i].fullname + "</option>";
            i++;
          }
          $("select#clients").html(options);
        });
      }
    });

- title "Bienvenidos"

/! Nav tabs
ul.nav.nav-tabs role="tablist" 
  li role="presentation" 
    a data-toggle="tab" href="#events" role="tab"  Eventos

  li role="presentation" 
    a data-toggle="tab" href="#group" role="tab"  Grupos
  li.active role="presentation" 
    a data-toggle="tab" href="#contacts" role="tab"  Contactos
  li role="presentation" 
    a data-toggle="tab" href="#memos" role="tab"  Memos
 
/! Tab panes
.tab-content
  #events.tab-pane.fade role="tabpanel"  ...
  #contacts.tab-pane.fade.in.active role="tabpanel"
    .row
      .col-md-6
        .form-group

          input name="search" id="search" type="text" value="" class="form-control input-sm" placeholder="Busqueda de contacto"
          br
          = select_tag :clients, options_for_select(@contacts.map{|c| [c.fullname, c.o_id]}),  multiple: true, class: "form-control input-sm select-list"

          
          br
          = link_to "Nuevo", "#{root_path}#contacts", class: "btn btn-primary btn-block"
      .col-md-6
        = form_for @contact do |f|
          - if @contact.errors.any?
            #error_explanation
              h2 = "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
              ul
                - @contact.errors.full_messages.each do |message|
                  li = message


          .form-group
            = f.text_field :first_name,  placeholder:"Nombre", class: "form-control input-sm"
          .form-group
            = f.text_field :last_name,  placeholder:"Apellidos",class: "form-control input-sm"

          .form-group
            = f.text_field :email,  placeholder:"Email",class: "form-control input-sm"
          .form-group
            = f.text_field :celphone,  placeholder:"Celular",class: "form-control input-sm"
          .form-group
            = f.text_field :phone,  placeholder:"Telefono",class: "form-control input-sm"
          .form-group
            = f.text_area :address,  placeholder:"Direccion",class: "form-control input-sm"
          .form-group
            = f.text_area :comments,  placeholder:"Comentario",class: "form-control input-sm"

          .form-group
            - unless @contact.id
              .actions = f.submit 'Agregar Contacto', class: "btn btn-info btn-block"
            - else
              .col-md-6
                .actions = f.submit 'Actualizar', class: "btn btn-info btn-block"
              .col-md-6
                .actions 
                  = link_to 'Borrar', @contact, data: {:confirm => "Esta seguro de eliminar #{@contact.fullname}"}, :method => :delete , class: "btn btn-warning btn-block"

  #memos.tab-pane.fade role="tabpanel"

app/views/layouts/application.html.slim
doctype html
html lang="es"
  head
    meta charset="utf-8"
    title = "Agenda"

    = stylesheet_link_tag 'agenda', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
    
  body class= "agenda"
    #body_page.container
      .row
        .col-md-12
          - if content_for?(:title)
            .page-header
              h1
                = content_for(:title).html_safe
              
          .page_content
            == yield
      hr
        p.text-center style="color:#ccc"
          |Desarrollado por Carlos Montalvo
          
    script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"
    javascript:
      window.jQuery || document.write('#{ escape_javascript(javascript_include_tag "jquery") }')

    = javascript_include_tag "agenda"

    = yield(:footer)

app/views/memos/_form.html.slim
= form_for @memo do |f|
  - if @memo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@memo.errors.count, "error")} prohibited this memo from being saved:"
      ul
        - @memo.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :archived
    = f.check_box :archived
  .actions = f.submit 'Save'

app/views/memos/edit.html.slim
h1 Editing memo

== render 'form'

= link_to 'Show', @memo
'|
= link_to 'Back', memos_path

app/views/memos/index.html.slim
h1 Listing memos

table
  thead
    tr
      th Content
      th Archived
      th
      th
      th

  tbody
    - @memos.each do |memo|
      tr
        td = memo.content
        td = memo.archived
        td = link_to 'Show', memo
        td = link_to 'Edit', edit_memo_path(memo)
        td = link_to 'Destroy', memo, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Memo', new_memo_path

app/views/memos/new.html.slim
h1 New memo

== render 'form'

= link_to 'Back', memos_path

app/views/memos/show.html.slim
p#notice = notice

p
  strong Content:
  = @memo.content
p
  strong Archived:
  = @memo.archived

= link_to 'Edit', edit_memo_path(@memo)
'|
= link_to 'Back', memos_path